const CartActionTypes = {
    ADD_ITEM: 'ADD_ITEM', 
    CLEAR_CART: 'CLEAR_CART',
    CLEAR_ITEM_FRON_CART:'CLEAR_ITEM_FRON_CART',
    REMOVE_ITEM: 'REMOVE_ITEM',
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN'
};

export default CartActionTypes;